### PR TITLE
changed the name of the use who claimed daily

### PR DESCRIPTION
**Pull request by m0nk3ybraindead**
changes:
- instead of using "them" we put the waifu's name
- the white space removal are my editor's fault :kyarubonked:

### CODE REVIEW

**Comment by HuyaneMatsu** [comment]
> the white space removal are my editor's fault :kyarubonked:

Please revert it.

**Comment by m0nk3ybraindead** [comment]
changed!

**Comment by HuyaneMatsu** [comment]
The code is broken. Would raise `NameError`.

**Comment by m0nk3ybraindead** [comment]
It's now broken't

**Comment by HuyaneMatsu** [comment]
👍🏻

**Pull request merged**
